### ISSUE TITLE
Finish How to get high-quality de novo variants from the output

### ISSUE THREAD

**Issue by husamia** [HKU-BAL/Clair3-Nova#2]
Can you please merge the high-quality de novo variants into a single command? this is the most important part of the branch

**Comment by aquaskyline** [comment]
you mean merge two VCFs?

**Comment by husamia** [comment]
> you mean merge two VCFs?

merging and filtering all the way to the final variants in vcf

**Comment by husamia** [comment]
this whole section https://github.com/HKU-BAL/Clair3-Nova?tab=readme-ov-file#how-to-get-high-quality-de-novo-variants-from-the-output

**Comment by aquaskyline** [comment]
Not merging these simple steps while they show user's what's going on in the back and offer better flexibility for customization.

**Comment by husamia** [comment]
What is TBC mean?

What is rtg? how to install it?

**Comment by sujunhao** [comment]
Hi @husamia, the [note](https://github.com/HKU-BAL/Clair3-Nova?tab=readme-ov-file#how-to-get-high-quality-de-novo-variants-from-the-output)  for how to get de novo variants has been updated, and the installation link for rtg tools is available in the description.

**Comment by husamia** [comment]
would it be possible to integrate the last step of getting the de novo variants into the script for running Clair3? and possibly having an updated Docker container for the required tools bcftools, rtg?

**Comment by husamia** [comment]
your novo the de novo model isn't clear. The calling is done independently for each of the family members it seem? then you filter for variants in the proband only? I don't see the advantage of this implementation over just calling each member independently then filtering for variants calls in the proband only. 
The way I would expect a real de novo calling would be to train and call variants based on trio then call the de novo variants in the entire trio. The error mode here is different from the normal germline calling. Most of the errors is false negatives in parents.

**Comment by sujunhao** [comment]
We provided several lines of script in the README for getting de novo variants from Clair3-Nova output. 

For the methodology of our tool,  we apply a trio neural network model to call variants from a trio. Some of the basic descriptions of the methodology are available in our Clair3-Trio paper.

**Comment by husamia** [comment]
Where can I download the reference file GCA_000001405.15_GRCh38_no_alt_analysis_set.sdf?

**Comment by husamia** [comment]
I converted the .fna reference to sdf with format. Now I am getting the error 

bcftools view -i "INFO/DNP>0.8.5" trio_all_denovo.vcf.gz -s AS41320 -O z -o trio_high_quality_denovo.vcf.gz
Error occurred while processing the filter "INFO/DNP>0.8.5" (2:2)

`Error occurred while processing the filter "INFO/DNP>0.8.5" (2:2)`

**Comment by husamia** [comment]
it should be "INFO/DNP>0.85"

**Comment by husamia** [comment]
I am only getting calls in one chromosome "chr1" for some reason... I am trying to diagnose the issue. I cant figure it out. the last file trio_m_ann.vcf.gz contains calls from all chromosomes so far the next file is not

**Comment by husamia** [comment]
for some reason the calls with PASS are only on the chr1 the rest of calls in chromosomes are non PASS. I was able to filter for all de novo though
