### ISSUE TITLE
Duplicate Program Record Error in BAM File Header

### ISSUE THREAD

**Issue by zaka-edd** [HKU-BAL/Clair3-Nova#3]
Hi,

I am encountering an error while trying to load the BAM file in IGV generated by Clair3-Nova. The specific error message is:
```
Error loading BAM file: java.lang.IllegalArgumentException: Program record with group id whatshap already exists in SAMFileHeader!
```

The command I have ran for Clair3-nova, from the docker container was:
```
    /opt/bin/run_clair3_nova.sh \
    --bam_fn_c=${proband_bam} \
    --bam_fn_p1=${father_bam} \
    --bam_fn_p2=${mother_bam} \
    --output=. \
    --ref_fn=${refCh} \
    --threads=${task.cpus} \
    --model_path_clair3="/opt/models/clair3_models/${params.model_C3}" \
    --model_path_clair3_nova="/opt/models/clair3_nova_models/${params.model_C3T}" \
    --sample_name_c=${sampleId}_clair3nova_proband \
    --sample_name_p1=${sampleId}_clair3nova_father \
    --sample_name_p2=${sampleId}_clair3nova_mother \
    --enable_output_phasing \
    --enable_output_haplotagging
```

I would appreciate any guidance on resolving this issue :)

Kind regards

**Comment by zaka-edd** [comment]
The error I am encountering arises due to duplicate program records in the BAM file's header, specifically related to the "whatshap" group ID. During the processing with Clair3-Nova, it appears that multiple instances of program records with the same ID are being generated, which leads to conflicts when loading the BAM file in IGV.

The two lines causing the conflict are:
```
@PG	PN:whatshap	ID:whatshap	VN:1.0	...
@PG	PN:whatshap	ID:whatshap	VN:1.7	...
```
Both lines share the same ID ("whatshap"), which is not allowed as each program record in the SAM file header must have a unique ID. This redundancy results in the error message.

 Hope this clarification helps in identifying and resolving the issue!

**Comment by sujunhao** [comment]
Hi,

Thank you for providing more information about the error. It seems that the issue arises from duplicate program records in the BAM file's header, specifically related to the "whatshap" group ID. Our program generates a new header line with the current version of Whathap (1.7), which conflicts with the existing header line with version 1.0.

As a quick workaround, you can try removing the old header line with version 1.0 using samtools reheader. You can find more information about this command in the Samtools documentation: http://www.htslib.org/doc/samtools-reheader.html.

We will consider adding error detection for this issue in our next update. Thank you for bringing this to our attention and helping us improve our package.

**Comment by sujunhao** [comment]
Hi,

I reviewed our program, and it only outputs a header line of: "@PG PN:whatshap ID:whatshap VN:1.7 .."

To remove the duplicated @PG lines for uploading to IGV, please consider using the following script:


```
ORI_BAM_FILE=you_bam_file.bam
NEW_BAM_FILE=new_bam_file.bam
samtools reheader -P -c 'grep -v PG.PN:whatshap.*VN:1.0' $ORI_BAM_FILE | samtools view -b -o $NEW_BAM_FILE
```

**Comment by zaka-edd** [comment]
Thank you for picking this up so quickly! :)
