### ISSUE TITLE
BAM output with only chr1 when enabling haplotype phasing

### ISSUE THREAD

**Issue by zaka-edd** [HKU-BAL/Clair3-Nova#4]
Hi,

I have an issue I hope you can help me with. I don't know if it is a bug or there is a easy work around. When I run Clair3-Nova with haplotype phasing enabled, I receive a BAM file containing only reads mapped to chr1. This appears to be due to missing contigs not being recognized in the VCF header, as I encountered the following error in the log:
``` ERROR: whatshap error: Input BAM/CRAM contains reads on contig 'chr1_KI270706v1_random', but that contig does not exist in the VCF header. To bypass this check, use --skip-missing-contigs ```

I suspect it is preventing proper inclusion of all contigs in the phased BAM output. I have attached the command log with additional details on the issue.
[run_clair3_nova.log](https://github.com/user-attachments/files/17554302/run_clair3_nova.log)

**Comment by zaka-edd** [comment]
I just found that in ```~/EP3247_clair3nova_proband/tmp/phase_output/phase_bam/``` There is a bam created for each chromosome for some reason they are just not merged after.

**Comment by aquaskyline** [comment]
As the error message suggested, it was from whatshap and because of a discrepancy between the sequences shown in the header of the BAM and those available in the reference. You can modify run_clair3_nova.sh and add `--skip-missing-contigs` to suppress the error.

**Comment by zaka-edd** [comment]
Can this be added as an option, as I like to run Clair3nova as a docker container?

**Comment by aquaskyline** [comment]
We'd suggest to use a complete BAM header to avoid the error.

**Comment by sujunhao** [comment]
Hi, The called variants should already be present in your output folder, specifically in the file "/net/prom9/prom9/study255_ONT_methylation_project/results/ep/study/hg38s/study255_ONT_methylation_project/zakaria/results/clair3nova/work/7f/447fade11390b29fb8fe89ef3449ad/./EP3247_clair3nova_proband.vcf.gz".

To resolve this issue, you can try one of the following options:

    Re-run the Whathap haplotagging step using your original files by yourself.
    Re-run the entire Clair3-Nova script with the additional option "--include_all_ctgs".

**Comment by sujunhao** [comment]
Hi, 

The "--skip-missing-contigs" flag is available in the latest github code now.

please using the following script to get the newest code:

```
# clone Clair3-Nova
git clone https://github.com/hku-bal/Clair3-Nova.git
cd Clair3-Nova

# build a docker image named hkubal/clair3-nova:latest
# might require docker authentication to build docker image 
docker build -f ./Dockerfile -t hkubal/clair3-nova:latest .

# run clair3-docker image like 
docker run -it hkubal/clair3-nova:latest /opt/bin/run_clair3_nova.sh --help
```

**Comment by zaka-edd** [comment]
Hi,
Thank you for adding it. I can confirm that adding the "--include_all_ctgs" flag indeed also solved the issue.
